# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json

minimum_prek_version = "0.4.12"

[[repos]]
repo = "meta"
hooks = [
  { id = "check-hooks-apply" }
]

# I'm excluding this because it's messing up the docs.
# Will consider adding back, although this has also been
# annoying for the JSONs too.
#
# [[repos]]
# repo = "https://github.com/pre-commit/mirrors-prettier"
# rev = "v3.1.0"
# hooks = [
#   { id = "prettier" }
# ]

[[repos]]
repo = "https://github.com/rhysd/actionlint"
rev = "914e7df21a07ef503a81201c76d2b11c789d3fca"  # frozen: v1.7.12
hooks = [
  { id = "actionlint" }
]

[[repos]]
repo = "https://github.com/tox-dev/pyproject-fmt"
rev = "b82a24a520c5d496cb7b23b4e9b63537c280f51b"  # frozen: v2.27.0
hooks = [
  { id = "pyproject-fmt" }
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "7c55798a78262d14b2074abf623d8a992ebb70d4"  # frozen: v0.16.2
hooks = [
  {
    id = "ruff-check",
    name = "Ruff",
    args = ["--fix"]
  },
  {
    id = "ruff-format",
    name = "Ruff format"
  }
]

[[repos]]
repo = "local"
hooks = [
  {
    id = "mypy",
    name = "mypy - Static type checking",
    description = "Mypy helps ensure that we use our functions and variables correctly by checking the types.",
    entry = "mypy",
    language = "system",
    types = ["python"],
    exclude = "^examples|^docs/",
    require_serial = true
  }
]

[[repos]]
repo = "https://github.com/codespell-project/codespell"
rev = "57b21406f092110c18776e39b0bda50d37c945c8"  # frozen: v2.4.3
hooks = [
  {
    id = "codespell",
    files = '^docs/.*\.md$',
    additional_dependencies = ["tomli"]
  }
]
