## run tests locally
## uvx --with tox-uv tox
[tox]
envlist = py38,py39,py310,py311,py312,py313,py314
skip_missing_interpreters = false

[testenv]
uv_python_preference = only-managed
deps = .[dev]
allowlist_externals = pytest
commands = pytest -q {posargs}
