// Shared helpers for the legacy feed endpoints (src/pages/feed_*.ts), which
// keep the URLs previously generated by the mkdocs-rss-plugin working.
// starlight-blog also generates its own feed at /blog/rss.xml.
import { getCollection, type CollectionEntry } from 'astro:content';
import { base } from './base';
// @ts-expect-error -- untyped project-local JavaScript module.
import { SITE_TAGLINE, SITE_TITLE } from './site.mjs';

export const FEED_TITLE: string = SITE_TITLE;
export const FEED_DESCRIPTION: string = SITE_TAGLINE;

export async function getBlogPosts(): Promise<CollectionEntry<'docs'>[]> {
  const posts = await getCollection(
    'docs',
    (entry) => entry.id.startsWith('blog/') && entry.data.date !== undefined
  );
  return posts.sort((a, b) => b.data.date!.getTime() - a.data.date!.getTime());
}

export function postPath(entry: CollectionEntry<'docs'>): string {
  return `${base}/${entry.id}/`;
}

export function postUrl(site: URL | undefined, entry: CollectionEntry<'docs'>): string {
  return new URL(postPath(entry), site).href;
}

// Excerpt delimiter marking the end of a post's summary. Markdown posts use an
// HTML comment; MDX posts use a JSX comment, since MDX forbids HTML comments.
const EXCERPT_DELIMITER = /<!--\s*excerpt\s*-->|\{\/\*\s*excerpt\s*\*\/\}/;

/**
 * Plain-text post excerpt for feed descriptions: the frontmatter `excerpt` if
 * set, otherwise the post body up to the excerpt delimiter.
 */

export function postExcerpt(entry: CollectionEntry<'docs'>): string | undefined {
  const source = entry.data.excerpt ?? entry.body?.split(EXCERPT_DELIMITER)[0];
  if (!source) return undefined;
  return source
    // Drop MDX import statements, which precede the excerpt in converted posts.
    .replace(/^\s*import\s.+$/gm, '')
    .replace(/!\[[^\]]*\]\([^)]*\)/g, '') // images
    .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1') // links -> text
    .replace(/[*_`]/g, '')
    .trim();
}

export function jsonFeed(site: URL | undefined, posts: CollectionEntry<'docs'>[]) {
  return Response.json({
    version: 'https://jsonfeed.org/version/1',
    title: FEED_TITLE,
    home_page_url: new URL(`${base}/`, site).href,
    description: FEED_DESCRIPTION,
    items: posts.map((entry) => ({
      id: postUrl(site, entry),
      url: postUrl(site, entry),
      title: entry.data.title,
      date_published: entry.data.date!.toISOString(),
    })),
  });
}
