// Shared helpers for the legacy feed endpoints (src/pages/feed_*.ts), which
// keep the URLs previously generated by the mkdocs-rss-plugin working.
// starlight-blog also generates its own feed at /blog/rss.xml.
import { getCollection, type CollectionEntry } from 'astro:content';

export const FEED_TITLE = 'rich-click';
export const FEED_DESCRIPTION = 'Richly rendered command line interfaces in click.';

const normalizedBase = `${import.meta.env.BASE_URL.replace(/\/$/, '')}/`;

export async function getBlogPosts(): Promise<CollectionEntry<'docs'>[]> {
  const posts = await getCollection(
    'docs',
    (entry) => entry.id.startsWith('blog/') && entry.data.date !== undefined
  );
  return posts.sort((a, b) => b.data.date!.getTime() - a.data.date!.getTime());
}

export function postPath(entry: CollectionEntry<'docs'>): string {
  return `${normalizedBase}${entry.id}/`;
}

export function postUrl(site: URL | undefined, entry: CollectionEntry<'docs'>): string {
  return new URL(postPath(entry), site).href;
}

export function jsonFeed(site: URL | undefined, posts: CollectionEntry<'docs'>[]) {
  return Response.json({
    version: 'https://jsonfeed.org/version/1',
    title: FEED_TITLE,
    home_page_url: new URL(normalizedBase, site).href,
    description: FEED_DESCRIPTION,
    items: posts.map((entry) => ({
      id: postUrl(site, entry),
      url: postUrl(site, entry),
      title: entry.data.title,
      date_published: entry.data.date!.toISOString(),
    })),
  });
}
