from typing import TYPE_CHECKING, Any, Callable, Dict, List, Literal, Optional


if TYPE_CHECKING:
    from rich.style import StyleType


# TODO: Optimize loading themes
#  No need to iterate over everything and store in memory.
#  Behaviors when combining themes is also weird
#  and can allow for more interesting variety.

ThemeType = Literal["color", "format", "combined"]


class RichTheme:
    """Rich theme. This sets defaults styling for the CLI."""

    def __init__(
        self,
        name: str,
        *,
        description: Optional[str] = None,
        styles: Optional[Dict[str, Any]] = None,
        primary_colors: Optional[List["StyleType"]] = None,
        post_combine_callback: Optional[Callable[[Dict[str, Any]], Dict[str, Any]]] = None,
    ) -> None:
        """
        Create RichTheme instance.

        Args:
        ----
            name: Name of the theme.
            description: Description for the theme.
            styles: Dict of styles that are applied.
            primary_colors: Description of which colors are applied. Does not do anything,
                just serves as documentation.
            post_combine_callback: After combining two themes, function is called which adjusts
                the styles.

        """
        self.name = name
        self.description = description
        self.styles = styles or {}
        self.primary_colors = primary_colors or []
        self.post_combine_callback = post_combine_callback

    def __repr__(self) -> str:
        return f"<{self.__class__.__name__} {self.name}>"

    def combine(self, other: "RichTheme") -> "RichTheme":
        styles = self.styles.copy()
        styles.update(other.styles)
        if self.post_combine_callback:
            styles = self.post_combine_callback(styles)
        if other.post_combine_callback:
            styles = other.post_combine_callback(styles)
        return self.__class__(
            name=f"{self.name}-{other.name}",
            styles=styles,
        )

    def __add__(self, other: "RichTheme") -> "RichTheme":
        return self.combine(other)

    def __radd__(self, other: "RichTheme") -> "RichTheme":
        return other.combine(self)


COLORS: Dict[str, Dict[str, Any]] = {
    "default": {
        "style_option": "bold cyan",
        "style_option_negative": None,
        "style_argument": "bold cyan",
        "style_command": "bold cyan",
        "style_command_aliases": "bold green",
        "style_switch": "bold green",
        "style_switch_negative": None,
        "style_metavar": "bold yellow",
        "style_metavar_append": "dim yellow",
        "style_metavar_separator": "dim",
        "style_usage": "yellow",
        "style_usage_command": "bold",
        "style_usage_separator": "",
        "style_options_panel_help_style": "dim",
        "style_commands_panel_help_style": "dim",
        "style_deprecated": "red",
        "style_options_table_border_style": "dim",
        "style_commands_table_border_style": "dim",
        "style_options_panel_border": "dim",
        "style_commands_panel_border": "dim",
        "style_options_panel_title_style": "",
        "style_commands_panel_title_style": "",
        "style_required_long": "dim red",
        "style_required_short": "red",
        "style_option_help": "",
        "style_command_help": "",
        "style_option_default": "dim",
        "style_option_envvar": "dim yellow",
        "style_helptext_first_line": "",
        "style_helptext": "dim",
        "style_header_text": "",
        "style_epilog_text": "",
        "style_footer_text": "",
        "style_options_panel_style": "none",
        "style_commands_panel_style": "none",
        "style_padding_usage": "none",
        "style_padding_helptext": "none",
        "style_padding_epilog": "none",
    },
    "solarized": {  # 30% done
        "style_option": "bold bright_blue",
        "style_option_negative": None,
        "style_argument": "bold green not dim",
        "style_command": "bold bright_yellow",
        "style_command_aliases": "bright_yellow",
        "style_usage_command": "bright_cyan",
        "style_usage_separator": "green",
        "style_switch": "bold blue",
        "style_switch_negative": None,
        "style_usage": "bold bright_yellow",
        "style_metavar_append": "yellow",
        "style_metavar": "bright_yellow",
        "style_metavar_separator": "bright_yellow",
        "style_options_panel_help_style": "cyan",
        "style_commands_panel_help_style": "yellow",
        "style_deprecated": "magenta",
        "style_options_table_border_style": "bright_cyan",
        "style_commands_table_border_style": "bright_yellow",
        "style_options_panel_border": "bright_cyan dim",
        "style_commands_panel_border": "bright_yellow dim",
        "style_options_panel_title_style": "bright_cyan not dim",
        "style_commands_panel_title_style": "bright_yellow not dim",
        "style_required_long": "magenta",
        "style_required_short": "bright_red",
        "style_option_help": "cyan",
        "style_command_help": "yellow",
        "style_option_default": "green",
        "style_option_envvar": "green",
        "style_helptext_first_line": "cyan",
        "style_helptext": "cyan",
        "style_header_text": "cyan",
        "style_epilog_text": "cyan",
        "style_footer_text": "cyan",
        "style_options_panel_style": "none",
        "style_commands_panel_style": "none",
        "style_padding_usage": "none",
        "style_padding_helptext": "none",
        "style_padding_epilog": "none",
    },
    "dracula": {
        "style_option": "bright_magenta",
        "style_option_negative": None,
        "style_argument": "not dim not bold bright_cyan",
        "style_command": "bright_cyan",
        "style_command_aliases": "bright_cyan",
        "style_usage_command": "white",
        "style_usage_separator": "dim bold bright_cyan",
        "style_switch": "bold bright_magenta",
        "style_switch_negative": None,
        "style_usage": "bold bright_red",
        "style_metavar_append": "bright_yellow",
        "style_metavar": "bright_yellow",
        "style_metavar_separator": "white",
        "style_options_panel_help_style": "not dim",
        "style_commands_panel_help_style": "not dim",
        "style_deprecated": "red",
        "style_options_table_border_style": "bold dim red",
        "style_commands_table_border_style": "bold dim cyan",
        "style_options_panel_border": "dim red",
        "style_commands_panel_border": "dim cyan",
        "style_options_panel_title_style": "not dim bold red",
        "style_commands_panel_title_style": "not dim bold cyan",
        "style_required_long": "bright_red",
        "style_required_short": "bright_red",
        "style_option_help": "white",
        "style_command_help": "bright_yellow",
        "style_option_default": "bright_green",
        "style_option_envvar": "bright_yellow",
        "style_helptext_first_line": "bright_magenta",
        "style_helptext": "white",
        "style_header_text": "",
        "style_epilog_text": "",
        "style_footer_text": "",
        "style_options_panel_style": "none",
        "style_commands_panel_style": "none",
        "style_padding_usage": "none",
        "style_padding_helptext": "none",
        "style_padding_epilog": "none",
    },
    "dracula2": {
        "style_option": "bright_magenta",
        "style_option_negative": None,
        "style_argument": "not dim not bold bright_cyan",
        "style_command": "bright_cyan",
        "style_command_aliases": "bright_cyan",
        "style_usage_command": "white",
        "style_usage_separator": "dim bold bright_cyan",
        "style_switch": "bold bright_magenta",
        "style_switch_negative": None,
        "style_usage": "bold bright_red",
        "style_metavar_append": "bright_yellow",
        "style_metavar": "bright_yellow",
        "style_metavar_separator": "white",
        "style_options_panel_help_style": "not dim",
        "style_commands_panel_help_style": "not dim",
        "style_deprecated": "red",
        "style_options_table_border_style": "bold dim red",
        "style_commands_table_border_style": "bold dim cyan",
        "style_options_panel_border": "dim red",
        "style_commands_panel_border": "dim cyan",
        "style_options_panel_title_style": "not dim bold red",
        "style_commands_panel_title_style": "not dim bold cyan",
        "style_required_long": "bright_red",
        "style_required_short": "bright_red",
        "style_option_help": "white",
        "style_command_help": "bright_yellow",
        "style_option_default": "bright_green",
        "style_option_envvar": "bright_yellow",
        "style_helptext_first_line": "bright_magenta",
        "style_helptext": "white",
        "style_header_text": "",
        "style_epilog_text": "",
        "style_footer_text": "",
        "style_options_panel_style": "white on black",
        "style_commands_panel_style": "white on black",
        "style_padding_usage": "white on black",
        "style_padding_helptext": "white on black",
        "style_padding_epilog": "white on black",
    },
    "star": {  # 100% done
        "style_option": "yellow",
        "style_option_negative": None,
        "style_argument": "bright_blue",
        "style_command": "yellow",
        "style_command_aliases": "yellow",
        "style_usage_command": "yellow",
        "style_usage_separator": "",
        "style_switch": "yellow",
        "style_switch_negative": None,
        "style_usage": "bold yellow",
        "style_metavar_append": "blue",
        "style_metavar": "blue",
        "style_metavar_separator": "",
        "style_options_panel_help_style": "dim blue",
        "style_commands_panel_help_style": "dim blue",
        "style_deprecated": "dim red",
        "style_options_table_border_style": "",
        "style_commands_table_border_style": "",
        "style_options_panel_border": "dim",
        "style_commands_panel_border": "dim",
        "style_options_panel_title_style": "default not dim",
        "style_commands_panel_title_style": "default not dim",
        "style_required_long": "dim red",
        "style_required_short": "dim red",
        "style_option_help": "default not bold",
        "style_command_help": "default not bold",
        "style_option_default": "dim default",
        "style_option_envvar": "dim blue",
        "style_helptext_first_line": "default",
        "style_helptext": "default",
        "style_header_text": "",
        "style_epilog_text": "",
        "style_footer_text": "",
        "style_options_panel_style": "none",
        "style_commands_panel_style": "none",
        "style_padding_usage": "none",
        "style_padding_helptext": "none",
        "style_padding_epilog": "none",
    },
    # Earthy
    "forest": {  # 100% done
        "style_option": "green",
        "style_option_negative": "magenta",
        "style_argument": "yellow",
        "style_command": "green",
        "style_command_aliases": "dim green",
        "style_usage_command": "green",
        "style_usage_separator": "",
        "style_switch": "bold green",
        "style_switch_negative": "bold magenta",
        "style_usage": "bold",
        "style_metavar_append": "yellow",
        "style_metavar": "yellow",
        "style_metavar_separator": "dim yellow",
        "style_options_panel_help_style": "italic cyan",
        "style_commands_panel_help_style": "italic cyan",
        "style_deprecated": "dim bright_green",
        "style_options_table_border_style": "dim yellow",
        "style_commands_table_border_style": "dim yellow",
        "style_options_panel_border": "dim yellow",
        "style_commands_panel_border": "dim yellow",
        "style_options_panel_title_style": "yellow not dim",
        "style_commands_panel_title_style": "yellow not dim",
        "style_required_long": "bright_green",
        "style_required_short": "bright_green",
        "style_option_help": "default not bold",
        "style_command_help": "default not bold",
        "style_option_default": "yellow",
        "style_option_envvar": "yellow",
        "style_helptext_first_line": "green",
        "style_helptext": "",
        "style_header_text": "cyan",
        "style_epilog_text": "cyan",
        "style_footer_text": "cyan",
        "style_options_panel_style": "none",
        "style_commands_panel_style": "none",
        "style_padding_usage": "none",
        "style_padding_helptext": "none",
        "style_padding_epilog": "none",
    },
    # Dark and unified color scheme, looks great with complex CLIs.
    "quartz": {  # 100% done
        "style_option": "bold magenta",
        "style_option_negative": None,
        "style_argument": "magenta not dim",
        "style_command": "bold blue",
        "style_command_aliases": "blue",
        "style_usage_command": "bright_blue",
        "style_usage_separator": "dim magenta",
        "style_switch": "bold magenta",
        "style_switch_negative": None,
        "style_usage": "bold",
        "style_metavar_append": "dim magenta",
        "style_metavar": "dim",
        "style_metavar_separator": "",
        "style_options_panel_help_style": "dim",
        "style_commands_panel_help_style": "dim",
        "style_deprecated": "dim red",
        "style_options_table_border_style": "dim magenta",
        "style_commands_table_border_style": "dim blue",
        "style_options_panel_border": "dim magenta",
        "style_commands_panel_border": "dim blue",
        "style_options_panel_title_style": "",
        "style_commands_panel_title_style": "",
        "style_required_long": "dim red",
        "style_required_short": "dim red",
        "style_option_help": "default not bold",
        "style_command_help": "default not bold",
        "style_option_default": "dim",
        "style_option_envvar": "dim bright_magenta",
        "style_helptext_first_line": "bold",
        "style_helptext": "",
        "style_header_text": "",
        "style_epilog_text": "dim",
        "style_footer_text": "dim",
        "style_options_panel_style": "none",
        "style_commands_panel_style": "none",
        "style_padding_usage": "none",
        "style_padding_helptext": "none",
        "style_padding_epilog": "none",
    },
    # Remix of quartz with accents
    "quartz2": {  # 100% done
        "style_option": "magenta",
        "style_option_negative": None,
        "style_argument": "yellow",
        "style_command": "blue",
        "style_command_aliases": "blue",
        "style_usage_command": "",
        "style_usage_separator": "",
        "style_switch": "bold magenta",
        "style_switch_negative": None,
        "style_usage": "blue",
        "style_metavar_append": "yellow",
        "style_metavar": "yellow",
        "style_metavar_separator": "dim",
        "style_options_panel_help_style": "yellow not dim italic",
        "style_commands_panel_help_style": "yellow not dim italic",
        "style_deprecated": "dim",
        "style_options_table_border_style": "dim magenta",
        "style_commands_table_border_style": "dim blue",
        "style_options_panel_border": "dim magenta",
        "style_commands_panel_border": "dim blue",
        "style_options_panel_title_style": "bold not dim",
        "style_commands_panel_title_style": "bold not dim",
        "style_required_long": "dim red",
        "style_required_short": "dim red",
        "style_option_help": "default not bold",
        "style_command_help": "default not bold",
        "style_option_default": "dim",
        "style_option_envvar": "dim yellow",
        "style_helptext_first_line": "",
        "style_helptext": "dim",
        "style_header_text": "blue",
        "style_epilog_text": "dim",
        "style_footer_text": "dim",
        "style_options_panel_style": "none",
        "style_commands_panel_style": "none",
        "style_padding_usage": "none",
        "style_padding_helptext": "none",
        "style_padding_epilog": "none",
    },
    # Theme based on cargo CLI. Legible and bold style.
    "cargo": {  # 100% done
        "style_option": "bold cyan",
        "style_option_negative": None,
        "style_argument": "cyan",
        "style_command": "bold cyan",
        "style_command_aliases": "bold cyan",
        "style_usage_command": "bold cyan",
        "style_usage_separator": "cyan",
        "style_switch": "bold cyan",
        "style_switch_negative": None,
        "style_usage": "bold green",
        "style_metavar_append": "cyan",
        "style_metavar": "cyan",
        "style_metavar_separator": "",
        "style_options_panel_help_style": "default not bold italic",
        "style_commands_panel_help_style": "default not bold italic",
        "style_deprecated": "dim",
        "style_options_table_border_style": "green",
        "style_commands_table_border_style": "green",
        "style_options_panel_border": "green",
        "style_commands_panel_border": "green",
        "style_options_panel_title_style": "bold",
        "style_commands_panel_title_style": "bold",
        "style_required_long": "",
        "style_required_short": "bright_red",
        "style_option_help": "default not bold",
        "style_command_help": "default not bold",
        "style_option_default": "",
        "style_option_envvar": "",
        "style_helptext_first_line": "",
        "style_helptext": "",
        "style_header_text": "",
        "style_epilog_text": "",
        "style_footer_text": "",
        "style_options_panel_style": "none",
        "style_commands_panel_style": "none",
        "style_padding_usage": "none",
        "style_padding_helptext": "none",
        "style_padding_epilog": "none",
    },
    "mono": {  # 100% done
        "style_option": "",
        "style_option_negative": None,
        "style_argument": "",
        "style_command": "",
        "style_command_aliases": "",
        "style_usage_command": "bold default",
        "style_usage_separator": "",
        "style_switch": "",
        "style_switch_negative": None,
        "style_usage": "bold",
        "style_metavar_append": "dim",
        "style_metavar": "dim",
        "style_metavar_separator": "",
        "style_options_panel_help_style": "dim italic",
        "style_commands_panel_help_style": "dim italic",
        "style_deprecated": "bold",
        "style_options_table_border_style": "",
        "style_commands_table_border_style": "",
        "style_options_panel_border": "dim",
        "style_commands_panel_border": "dim",
        "style_options_panel_title_style": "bold not dim",
        "style_commands_panel_title_style": "bold not dim",
        "style_required_long": "bold",
        "style_required_short": "dim bold",
        "style_option_help": "default not bold",
        "style_command_help": "default not bold",
        "style_option_default": "dim",
        "style_option_envvar": "dim",
        "style_helptext_first_line": "",
        "style_helptext": "dim",
        "style_header_text": "",
        "style_epilog_text": "",
        "style_footer_text": "",
        "style_options_panel_style": "none",
        "style_commands_panel_style": "none",
        "style_padding_usage": "none",
        "style_padding_helptext": "none",
        "style_padding_epilog": "none",
    },
    **{
        f"{c}1": {  # 100% done
            "style_option": "",
            "style_option_negative": None,
            "style_argument": "",
            "style_command": "",
            "style_command_aliases": "",
            "style_usage_command": "bold",
            "style_usage_separator": "",
            "style_switch": "",
            "style_switch_negative": None,
            "style_usage": f"bold {c}",
            "style_metavar_append": "dim",
            "style_metavar": "dim",
            "style_metavar_separator": "",
            "style_options_panel_help_style": f"dim italic bright_{c}",
            "style_commands_panel_help_style": f"dim italic bright_{c}",
            "style_deprecated": f"{c}",
            "style_options_table_border_style": f"dim {c}",
            "style_commands_table_border_style": f"dim {c}",
            "style_options_panel_border": f"dim {c}",
            "style_commands_panel_border": f"dim {c}",
            "style_options_panel_title_style": f"bold {c}",
            "style_commands_panel_title_style": f"bold {c}",
            "style_required_long": f"{c}",
            "style_required_short": f"bold {c}",
            "style_option_help": "default not bold",
            "style_command_help": "default not bold",
            "style_option_default": "dim",
            "style_option_envvar": "dim",
            "style_helptext_first_line": "",
            "style_helptext": "dim",
            "style_header_text": "",
            "style_epilog_text": "",
            "style_footer_text": "",
            "style_options_panel_style": "none",
            "style_commands_panel_style": "none",
            "style_padding_usage": "none",
            "style_padding_helptext": "none",
            "style_padding_epilog": "none",
        }
        for c in ["red", "green", "yellow", "blue", "magenta", "cyan"]
    },
    **{
        f"{c}2": {  # 100% done
            "style_option": f"{c}",
            "style_option_negative": None,
            "style_argument": f"{c}",
            "style_command": f"{c}",
            "style_command_aliases": f"{c}",
            "style_usage_command": "bold",
            "style_usage_separator": "",
            "style_switch": f"bold {c}",
            "style_switch_negative": None,
            "style_usage": f"bold {c}",
            "style_metavar_append": f"dim {c}",
            "style_metavar": f"dim {c}",
            "style_metavar_separator": "",
            "style_options_panel_help_style": "dim italic",
            "style_commands_panel_help_style": "dim italic",
            "style_deprecated": f"{c}",
            "style_options_table_border_style": "dim",
            "style_commands_table_border_style": "dim",
            "style_options_panel_border": "dim",
            "style_commands_panel_border": "dim",
            "style_options_panel_title_style": "not dim",
            "style_commands_panel_title_style": "not dim",
            "style_required_long": f"{c}",
            "style_required_short": f"bold {c}",
            "style_option_help": "default not bold",
            "style_command_help": "default not bold",
            "style_option_default": "dim",
            "style_option_envvar": "dim",
            "style_helptext_first_line": "",
            "style_helptext": "dim",
            "style_header_text": "",
            "style_epilog_text": "",
            "style_footer_text": "",
            "style_options_panel_style": "none",
            "style_commands_panel_style": "none",
            "style_padding_usage": "none",
            "style_padding_helptext": "none",
            "style_padding_epilog": "none",
        }
        for c in ["red", "green", "yellow", "blue", "magenta", "cyan"]
    },
    "nord": {  # 100% done
        "style_option": "bold bright_blue",
        "style_option_negative": None,
        "style_argument": "bold bright_blue",
        "style_command": "bold bright_cyan",
        "style_command_aliases": "magenta not bold",
        "style_usage_command": "bold bright_cyan",
        "style_usage_separator": "bright_blue",
        "style_switch": "blue",
        "style_switch_negative": None,
        "style_usage": "bold",
        "style_metavar_append": "dim magenta",
        "style_metavar": "not bold magenta",
        "style_metavar_separator": "bold",
        "style_options_panel_help_style": "default",
        "style_commands_panel_help_style": "default",
        "style_deprecated": "bright_magenta",
        "style_options_table_border_style": "dim blue",
        "style_commands_table_border_style": "dim cyan",
        "style_options_panel_border": "dim bright_blue",
        "style_commands_panel_border": "dim bright_cyan",
        "style_options_panel_title_style": "",
        "style_commands_panel_title_style": "",
        "style_required_long": "bright_magenta",
        "style_required_short": "bold dim bright_magenta",
        "style_option_help": "default not bold",
        "style_command_help": "default not bold",
        "style_option_default": "magenta",
        "style_option_envvar": "green",
        "style_helptext_first_line": "cyan",
        "style_helptext": "default",
        "style_header_text": "default",
        "style_epilog_text": "default",
        "style_footer_text": "default",
        "style_options_panel_style": "none",
        "style_commands_panel_style": "none",
        "style_padding_usage": "none",
        "style_padding_helptext": "none",
        "style_padding_epilog": "none",
    },
    "plain": {  # 100% done
        "style_option": "default",
        "style_option_negative": None,
        "style_argument": "default",
        "style_command": "default",
        "style_command_aliases": "default",
        "style_usage_command": "default",
        "style_usage_separator": "default",
        "style_switch": "default",
        "style_switch_negative": None,
        "style_usage": "default",
        "style_metavar_append": "default",
        "style_metavar": "default",
        "style_metavar_separator": "default",
        "style_options_panel_help_style": "default",
        "style_commands_panel_help_style": "default",
        "style_deprecated": "default",
        "style_options_table_border_style": "default",
        "style_commands_table_border_style": "default",
        "style_options_panel_border": "default",
        "style_commands_panel_border": "default",
        "style_options_panel_title_style": "default",
        "style_commands_panel_title_style": "default",
        "style_required_long": "default",
        "style_required_short": "default",
        "style_option_help": "default",
        "style_command_help": "default",
        "style_option_default": "default",
        "style_option_envvar": "default",
        "style_helptext_first_line": "default",
        "style_helptext": "default",
        "style_header_text": "default",
        "style_epilog_text": "default",
        "style_footer_text": "default",
        "style_options_panel_style": "none",
        "style_commands_panel_style": "none",
        "style_padding_usage": "none",
        "style_padding_helptext": "none",
        "style_padding_epilog": "none",
    },
}

FORMATS: Dict[str, Dict[str, Any]] = {
    # Classic rich-click format with boxes
    "box": {
        "style_options_panel_box": "ROUNDED",
        "style_commands_panel_box": "ROUNDED",
        "style_options_table_box": None,
        "style_commands_table_box": None,
        "style_options_panel_padding": (0, 1),
        "style_commands_panel_padding": (0, 1),
        "panel_inline_help_in_title": False,
        "panel_inline_help_delimiter": " - ",
        "options_table_column_types": ["required", "opt_long", "opt_short", "metavar", "help"],
        "commands_table_column_types": ["name", "aliases", "help"],
        "panel_title_string": "{}",
        "deprecated_string": "\\[deprecated]",
        "deprecated_with_reason_string": "\\[deprecated: {}]",
        "default_string": "\\[default: {}]",
        "envvar_string": "\\[env var: {}]",
        "required_long_string": "\\[required]",
        "range_string": "[{}]",
        "required_short_string": "*",
        "padding_header_text": (1, 1, 0, 1),
        "padding_helptext": (0, 1, 1, 1),
        "padding_usage": 1,
        "delimiter_comma": ",",
        "delimiter_slash": "/",
        "panel_title_padding": 1,
        "padding_epilog": 1,
        "append_metavars_help_string": "\\[{}]",
        # "padding_footer_text": (1, 1, 0, 1),
        # "padding_errors_panel": (0, 0, 1, 0),
        # "padding_errors_suggestion": (0, 1, 0, 1),
        # "padding_errors_epilogue": (0, 1, 1, 1),
    },
    # Great balance of compactness, legibility, and style
    "nu": {
        "style_options_panel_box": "HORIZONTALS_DOUBLE_TOP",
        "style_commands_panel_box": "HORIZONTALS_DOUBLE_TOP",
        "style_options_table_box": None,
        "style_commands_table_box": None,
        "panel_title_string": "{}",
        "style_options_panel_padding": 0,
        "style_commands_panel_padding": 0,
        "deprecated_string": "(Deprecated)",
        "deprecated_with_reason_string": "(Deprecated: {})",
        "default_string": "(Default: {})",
        "envvar_string": "(Env: {})",
        "required_long_string": "(Required)",
        "range_string": "{}",
        "append_metavars_help_string": "\\[{}]",
        "required_short_string": "#",
        "padding_header_text": (0, 1, 1, 1),
        "padding_helptext": (0, 1, 1, 1),
        "padding_usage": (0, 1, 1, 1),
        "delimiter_comma": ",",
        "delimiter_slash": "/",
        "panel_title_padding": 1,
        "options_table_column_types": ["required", "opt_long", "opt_short", "metavar", "help"],
        "commands_table_column_types": ["name", "aliases", "help"],
        "panel_inline_help_delimiter": " - ",
        "padding_epilog": (0, 0, 1, 0),
        "panel_inline_help_in_title": False,
    },
    # Simple, classic, no-fuss CLI format
    "slim": {
        "style_options_panel_box": "BLANK",
        "style_commands_panel_box": "BLANK",
        "style_options_table_box": None,
        "style_commands_table_box": None,
        "panel_title_string": "{}:",
        "style_options_panel_padding": (0, 0, 0, 1),
        "style_commands_panel_padding": (0, 0, 0, 1),
        "padding_header_text": (0, 0, 1, 0),
        "padding_helptext": (0, 0, 1, 0),
        "padding_usage": (0, 0, 1, 0),
        "padding_epilog": (0, 0, 1, 0),
        "options_table_column_types": ["opt_short", "opt_long_metavar", "help"],
        "commands_table_column_types": ["name_with_aliases", "help"],
        # "options_table_column_types": ["opt_all", "metavar", "help"],
        "append_metavars_help_string": "<{}>",
        "envvar_string": "\\[env: {}=]",
        "delimiter_comma": ", ",
        "delimiter_slash": "/",
        "panel_title_padding": 0,
        "panel_inline_help_in_title": True,
        "panel_inline_help_delimiter": " ",
        "style_errors_panel_box": None,
        "deprecated_string": "\\[deprecated]",
        "deprecated_with_reason_string": "\\[deprecated: {}]",
        "default_string": "\\[default={}]",
        "required_long_string": "\\[required]",
        "range_string": "{}",
        "required_short_string": "*",
    },
    # Beautiful modern look
    "modern": {
        "style_options_panel_box": None,
        "style_commands_panel_box": None,
        "style_errors_panel_box": None,
        "style_options_table_box": "HORIZONTALS_TOP",
        "style_commands_table_box": "HORIZONTALS_TOP",
        "panel_title_string": "{}",
        "style_options_panel_padding": (0, 1),
        "style_commands_panel_padding": (0, 1),
        "padding_header_text": (1, 3, 0, 3),
        "padding_helptext": (0, 3, 1, 3),
        "padding_usage": (1, 3, 1, 3),
        "options_table_column_types": ["opt_short", "opt_long", "metavar", "help"],
        "commands_table_column_types": ["name", "aliases", "help"],
        "deprecated_string": "\\[deprecated]",
        "deprecated_with_reason_string": "\\[deprecated: {}]",
        "envvar_string": "\\[env={}]",
        "default_string": "\\[default={}]",
        "append_metavars_help_string": "\\[{}\\]",
        "panel_inline_help_in_title": True,
        "delimiter_comma": ", ",
        "delimiter_slash": " / ",
        "panel_title_padding": 1,
        "required_short_string": "*",
        "panel_inline_help_delimiter": " - ",
        "required_long_string": "\\[required]",
        "range_string": "[{}]",
        "padding_epilog": (0, 0, 1, 0),
    },
    # Spacious with sharp corners
    "robo": {
        "style_options_panel_box": "SQUARE",
        "style_commands_panel_box": "SQUARE",
        "style_options_table_box": None,
        "style_commands_table_box": None,
        "style_options_panel_padding": (1, 2),
        "style_commands_panel_padding": (1, 2),
        "padding_header_text": (0, 0, 1, 0),
        "padding_helptext": (0, 0, 1, 0),
        "padding_usage": (0, 0, 1, 0),
        "deprecated_string": "❮[b]DEPRECATED[/b]❯",
        "deprecated_with_reason_string": "❮[b]DEPRECATED:[/b] {}❯",
        "envvar_string": "❮[b]ENV:[/b] {}❯",
        "default_string": "❮[b]DEFAULT:[/b] {}❯",
        "append_metavars_help_string": "❮{}❯",
        "required_short_string": "*",
        "required_long_string": "❮[b]REQUIRED[/b]❯",
        "range_string": "{}",
        "options_table_column_types": ["opt_primary", "opt_secondary", "metavar", "help"],
        "commands_table_column_types": ["name", "aliases", "help"],
        "delimiter_comma": ", ",
        "delimiter_slash": " / ",
        "panel_title_padding": 2,
        "panel_title_string": "{}",
        "panel_inline_help_delimiter": " - ",
        "padding_epilog": (0, 0, 1, 0),
        "panel_inline_help_in_title": False,
    },
}

THEMES: Dict[str, Dict[str, Any]] = {}

for fk, fv in FORMATS.items():
    for ck, cv in COLORS.items():
        THEMES[f"{ck}-{fk}"] = {**cv, **fv}
        if ck in {"plain", "mono"}:
            THEMES[f"{ck}-{fk}"]["delimiter_comma"] = ", "
            THEMES[f"{ck}-{fk}"]["delimiter_slash"] = " / "
        # if fk in {"modern", "slim", "robo"}:
        for k in ["style_options_panel_title_style", "style_commands_panel_title_style"]:
            v = THEMES[f"{ck}-{fk}"].get(k, "")
            if "dim" not in v.split(" "):
                v = f"{v} not dim".strip()
            THEMES[f"{ck}-{fk}"][k] = v

for k, v in FORMATS.items():
    THEMES[k] = {**COLORS["default"], **v}

for k, v in COLORS.items():
    THEMES[k] = {**v, **FORMATS["box"]}
