name: Lint code
on:
  push:
  pull_request:

permissions: {}

jobs:
  prek:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set up Python
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          python-version: 3
          activate-environment: true
      - name: Install dependencies
        run: uv sync --active
      - name: Run prek
        run: prek run -a
