name: Test Coverage

on:
  push:
  pull_request:

permissions: {}

jobs:
  test:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    strategy:
      matrix:
        python: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        click: [8.0.*, 8.1.*, 8.2.*, 8.3.*, 8.4.*]
        rich: [12.*, 13.*, 14.*, 15.*]
        typer: [0.17.*, 0.25.*]
        exclude:
          - typer: 0.25.*
            rich: 12.*
          - click: 8.0.*
            typer: 0.25.*
          - click: 8.1.*
            typer: 0.25.*
          - click: 8.2.*
            typer: 0.25.*
    steps:
      - name: Check out the repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Set up Python
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          python-version: ${{ matrix.python }}
          activate-environment: true

      - name: Install dependencies
        run: |
          uv pip install ".[dev]"
          uv pip install --upgrade "click==$CLICK_VERSION" "rich==$RICH_VERSION" "typer==$TYPER_VERSION" --prerelease=allow
        env:
          CLICK_VERSION: ${{ matrix.click }}
          RICH_VERSION: ${{ matrix.rich }}
          TYPER_VERSION: ${{ matrix.typer }}

      - name: Run tests
        run: pytest --cov --cov-report term
