name: Test Coverage

on:
  push:
  pull_request:

permissions: {}

jobs:
  test:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    strategy:
      matrix:
        python: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        click: [8.0.*, 8.1.*, 8.2.*, 8.3.*, 8.4.*]
        rich: [12.*, 13.*, 14.*, 15.*]
        typer: [0.17.*, 0.25.*]
        exclude:
          - typer: 0.25.*
            rich: 12.*
          - click: 8.0.*
            typer: 0.25.*
          - click: 8.1.*
            typer: 0.25.*
          - click: 8.2.*
            typer: 0.25.*
    steps:
      - name: Check out the repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Python
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          python-version: ${{ matrix.python }}
          activate-environment: true

      - name: Run tests
        run: |
          uv run \
            --with "click==$CLICK_VERSION" \
            --with "rich==$RICH_VERSION" \
            --with "typer==$TYPER_VERSION" \
            --prerelease=allow \
            pytest --cov --cov-report term
        env:
          CLICK_VERSION: ${{ matrix.click }}
          RICH_VERSION: ${{ matrix.rich }}
          TYPER_VERSION: ${{ matrix.typer }}
